// Post-build steps for a low-bandwidth audience. Runs after the client and SSR
// builds (`npm run build`); uses only Node built-ins, no extra dependency.
//
// 1. Prerender: write the French page's HTML into dist/index.html, so the page
//    is readable as soon as the HTML arrives, before any JavaScript.
// 2. Service worker: precache the page and its hashed assets, so repeat visits
//    cost nothing and the site opens offline (a merchant demo in a market with
//    no signal).
// 3. Precompress: .br and .gz next to every text file, for hosts that serve
//    precompressed files (Brotli is ~15–20% smaller than gzip on this bundle).
// 4. Report the bytes that actually travel.

import { createHash } from 'node:crypto'
import { readdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'
import { brotliCompressSync, constants, gzipSync } from 'node:zlib'

const dist = new URL('../dist/', import.meta.url).pathname
const ssr = new URL('../dist-ssr/', import.meta.url).pathname

async function walk(dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...(await walk(full)))
    else out.push(full)
  }
  return out
}

// --- 1. Prerender ------------------------------------------------------------
const { render } = await import(join(ssr, 'entry-server.js'))
const indexPath = join(dist, 'index.html')
const template = await readFile(indexPath, 'utf8')
if (!template.includes('<div id="root"></div>')) throw new Error('root placeholder not found in dist/index.html')
const html = template.replace('<div id="root"></div>', `<div id="root">${render()}</div>`)
await writeFile(indexPath, html)
await rm(ssr, { recursive: true, force: true })

// --- 2. Service worker --------------------------------------------------------
const files = (await walk(dist))
  .map((f) => '/' + relative(dist, f))
  .filter((p) => !/\.(br|gz)$/.test(p) && !p.endsWith('/_headers') && !p.endsWith('/OFL.txt'))
  .filter((p) => p !== '/index.html')
const precache = ['/', ...files.sort()]
const version = createHash('sha256').update(html).update(precache.join('\n')).digest('hex').slice(0, 12)

const sw = `// Generated by scripts/postbuild.mjs. Do not edit.
const CACHE = 'hossouko-${version}'
const PRECACHE = ${JSON.stringify(precache)}

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return

  // The page: network first, so a published change is seen at once, with a
  // short timeout, because on a weak signal a stale page now beats a fresh
  // page in thirty seconds. Falls back to the cached page offline.
  if (req.mode === 'navigate') {
    event.respondWith(
      new Promise((resolve) => {
        let settled = false
        const fallback = () => caches.match('/').then((r) => { if (!settled) { settled = true; resolve(r || fetch(req)) } })
        const timer = setTimeout(fallback, 3500)
        fetch(req)
          .then((res) => {
            clearTimeout(timer)
            if (!settled) { settled = true; resolve(res) }
            if (res.ok) caches.open(CACHE).then((c) => c.put('/', res.clone()))
          })
          .catch(() => { clearTimeout(timer); fallback() })
      }),
    )
    return
  }

  // Hashed assets and fonts never change under the same name: cache first.
  event.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)) }
      return res
    })),
  )
})
`
await writeFile(join(dist, 'sw.js'), sw)

// --- 3. Precompress -----------------------------------------------------------
const compressible = /\.(html|js|css|svg|txt|json)$/
const rows = []
for (const file of await walk(dist)) {
  if (/\.(br|gz)$/.test(file)) continue
  const buf = await readFile(file)
  const rel = '/' + relative(dist, file)
  if (compressible.test(file)) {
    const br = brotliCompressSync(buf, { params: { [constants.BROTLI_PARAM_QUALITY]: 11 } })
    const gz = gzipSync(buf, { level: 9 })
    await writeFile(file + '.br', br)
    await writeFile(file + '.gz', gz)
    rows.push([rel, buf.length, gz.length, br.length])
  } else {
    rows.push([rel, (await stat(file)).size, null, null])
  }
}

// --- 4. Report ------------------------------------------------------------------
const kb = (n) => (n == null ? '     -' : (n / 1024).toFixed(1).padStart(6))
rows.sort((a, b) => b[1] - a[1])
console.log('\nBytes on the wire (KB)            raw   gzip brotli')
for (const [rel, raw, gz, br] of rows) console.log(`${rel.padEnd(32)}${kb(raw)} ${kb(gz)} ${kb(br)}`)

const first = rows.filter(([rel]) => rel === '/index.html' || (/^\/assets\/index-.*\.(js|css)$/.test(rel)))
const firstBr = first.reduce((n, [, raw, , br]) => n + (br ?? raw), 0) + 15040
console.log(`\nFirst visit, French, brotli + serif font: ~${(firstBr / 1024).toFixed(0)} KB`)
